openapi: 3.2.0
info:
  description: API documentation of Admin Portal
  title: Admin Portal Web Analytics API
  version: v0.0.1
servers:
- url: https://{tenant}
  variables:
    tenant:
      default: example.strivacity.com
      description: Your Strivacity tenant
tags:
- name: Web Analytics
paths:
  /admin/api/v1/instance/webAnalytics:
    get:
      description: 'You can list the existing web analytics integrations by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | read:config_instance_webanalytics |'
      operationId: list_3
      parameters:
      - description: Zero-based page index (0..N)
        in: query
        name: page
        schema:
          type: integer
          format: int64
          default: 0
      - description: The size of the page to be returned
        in: query
        name: size
        schema:
          type: integer
          format: int64
          default: 20
      - description: 'Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'
        in: query
        name: sort
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PagedModelWebAnalyticsResponse'
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
      security:
      - securityScheme:
        - read:config_instance_webanalytics
      summary: List web analytics integrations
      tags:
      - Web Analytics
    post:
      description: 'You can create a web analytics integration by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | write:config_instance_webanalytics |'
      operationId: create_4
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebAnalytics_WebAnalytics'
        required: true
      responses:
        '201':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebAnalytics_WebAnalytics'
          description: Created
        '400':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Bad Request
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '409':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Conflict
      security:
      - securityScheme:
        - write:config_instance_webanalytics
      summary: Create a web analytics integration
      tags:
      - Web Analytics
  /admin/api/v1/instance/webAnalytics/{id}:
    delete:
      description: 'You can delete a web analytics integration by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | delete:config_instance_webanalytics |'
      operationId: delete_5
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          enum:
          - googleAnalytics
          - googleTagManager
          - mixpanel
          - amplitude
      responses:
        '204':
          description: No Content
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
      security:
      - securityScheme:
        - delete:config_instance_webanalytics
      summary: Delete a web analytics integration
      tags:
      - Web Analytics
    get:
      description: 'You can get a web analytics integration by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | read:config_instance_webanalytics |'
      operationId: get_3
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          enum:
          - googleAnalytics
          - googleTagManager
          - mixpanel
          - amplitude
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebAnalyticsResponse_WebAnalytics'
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
      security:
      - securityScheme:
        - read:config_instance_webanalytics
      summary: Get a web analytics integration
      tags:
      - Web Analytics
    put:
      description: 'You can update a web analytics integration by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | write:config_instance_webanalytics |'
      operationId: update_3
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
          enum:
          - googleAnalytics
          - googleTagManager
          - mixpanel
          - amplitude
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebAnalytics_WebAnalytics'
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WebAnalytics_WebAnalytics'
          description: OK
        '400':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Bad Request
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
      security:
      - securityScheme:
        - write:config_instance_webanalytics
      summary: Update a web analytics integration
      tags:
      - Web Analytics
components:
  schemas:
    ProblemJson:
      type: object
      properties:
        detail:
          type: string
        entityName:
          type: string
          description: The name of the entity within the error has occurred
        errorKey:
          type: string
          description: A unique identifier of the error
        fieldErrors:
          type: array
          description: Field constraint violation errors
          items:
            $ref: '#/components/schemas/FieldError'
        message:
          type: string
          description: A unique identifier in format of 'error.{errorKey}'
        params:
          type: array
          description: Further information related to the actual error
          items:
            type: object
            additionalProperties:
              type: object
        path:
          type: string
          description: Request URI
        status:
          type: integer
          description: Status code
          format: int32
        title:
          type: string
      description: Based on [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807)
    WebAnalytics_WebAnalytics:
      required:
      - apiKey
      - configuration
      - id
      type: object
      properties:
        apiKey:
          maxLength: 512
          minLength: 1
          type: string
        configuration:
          maxLength: 256000
          minLength: 1
          type: string
          description: Provider specific configuration in raw text format.
        enabled:
          type: boolean
          default: true
        id:
          type: string
          enum:
          - googleAnalytics
          - googleTagManager
          - mixpanel
          - amplitude
      description: Represents web analytics configuration.
    FieldError:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
        objectName:
          type: string
    PageMetadata:
      type: object
      properties:
        number:
          type: integer
          format: int64
        size:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
    WebAnalyticsResponse:
      type: object
      properties:
        apiKey:
          type: string
        configuration:
          type: string
        enabled:
          type: boolean
        id:
          type: string
          enum:
          - googleAnalytics
          - googleTagManager
          - mixpanel
          - amplitude
    PagedModelWebAnalyticsResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/WebAnalyticsResponse'
        page:
          $ref: '#/components/schemas/PageMetadata'
    WebAnalyticsResponse_WebAnalytics:
      type: object
      properties:
        apiKey:
          type: string
        configuration:
          type: string
        enabled:
          type: boolean
        id:
          type: string
          enum:
          - googleAnalytics
          - googleTagManager
          - mixpanel
          - amplitude
  securitySchemes:
    securityScheme:
      scheme: bearer
      type: http
