openapi: 3.2.0
info:
  description: API documentation of Admin Portal - Admin Management
  title: Admin Portal - Admin Management Admin Claim API
  version: v0.0.1
servers:
- url: https://{tenant}
  variables:
    tenant:
      default: example.strivacity.com
      description: Your Strivacity tenant
tags:
- name: Admin Claim
paths:
  /admin/api/v1/admin/identityStore/availableNativeClaims:
    get:
      description: 'You can list the native claims that are still not assigned to an account attribute.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | read:config_admin_identity_store |'
      operationId: getAvailableNativeClaims
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NativeClaimResponse_NativeClaim'
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
      security:
      - securityScheme:
        - read:config_admin_identity_store
      summary: List available native claims
      tags:
      - Admin Claim
  /admin/api/v1/admin/identityStore/nativeClaimMappings:
    get:
      description: 'You can list the native claims with the assigned account attributes.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | read:config_admin_identity_store |'
      operationId: getNativeClaimMappings
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
      security:
      - securityScheme:
        - read:config_admin_identity_store
      summary: List native claim mappings
      tags:
      - Admin Claim
components:
  schemas:
    ProblemJson:
      type: object
      properties:
        detail:
          type: string
        entityName:
          type: string
          description: The name of the entity within the error has occurred
        errorKey:
          type: string
          description: A unique identifier of the error
        fieldErrors:
          type: array
          description: Field constraint violation errors
          items:
            $ref: '#/components/schemas/FieldError'
        message:
          type: string
          description: A unique identifier in format of 'error.{errorKey}'
        params:
          type: array
          description: Further information related to the actual error
          items:
            type: object
            additionalProperties:
              type: object
        path:
          type: string
          description: Request URI
        status:
          type: integer
          description: Status code
          format: int32
        title:
          type: string
      description: Based on [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807)
    NativeClaimResponse_NativeClaim:
      type: object
      properties:
        description:
          type: string
        dialectUri:
          type: string
        displayName:
          type: string
        id:
          type: string
        name:
          type: string
        readonly:
          type: boolean
        targetReadonly:
          type: boolean
    FieldError:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
        objectName:
          type: string
  securitySchemes:
    securityScheme:
      scheme: bearer
      type: http
