openapi: 3.2.0
info:
  description: API documentation of Admin Portal - Admin Management
  title: Admin Portal - Admin Management Admin Role API
  version: v0.0.1
servers:
- url: https://{tenant}
  variables:
    tenant:
      default: example.strivacity.com
      description: Your Strivacity tenant
tags:
- name: Admin Role
paths:
  /admin/api/v1/admin/identityStore/roles:
    get:
      description: 'You can list the existing admin role by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | read:config_admin_identity_store |'
      operationId: list
      parameters:
      - description: Role IDs used for filtering
        in: query
        name: ids
        required: false
        schema:
          uniqueItems: true
          type: array
          items:
            type: string
      - description: Name used for filtering
        in: query
        name: name
        required: false
        schema:
          type: string
      - description: Zero-based page index (0..N)
        in: query
        name: page
        schema:
          type: integer
          format: int64
          default: 0
      - description: The size of the page to be returned
        in: query
        name: size
        schema:
          type: integer
          format: int64
          default: 20
      - description: 'Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'
        in: query
        name: sort
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PagedModelAdminRoleResponse'
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
      security:
      - securityScheme:
        - read:config_admin_identity_store
      summary: List admin roles
      tags:
      - Admin Role
    post:
      description: 'You can create an admin role by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | write:config_admin_identity_store |'
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminRole_InsertRequest'
        required: true
      responses:
        '201':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AdminRoleResponse_AdminRole'
          description: Created
        '400':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Bad Request
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '409':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Conflict
      security:
      - securityScheme:
        - write:config_admin_identity_store
      summary: Create an admin role
      tags:
      - Admin Role
  /admin/api/v1/admin/identityStore/roles/scopes:
    get:
      description: 'You can list the existing scopes by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | read:config_admin_identity_store |'
      operationId: getAllScopes
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScopeAdminResponse_AdminRole'
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
      security:
      - securityScheme:
        - read:config_admin_identity_store
      summary: List scopes
      tags:
      - Admin Role
  /admin/api/v1/admin/identityStore/roles/{id}:
    delete:
      description: 'You can delete an admin role by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | write:config_admin_identity_store |'
      operationId: delete_2
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No Content
        '400':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Roles that has accounts assigned to cannot be deleted.
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '409':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Admin role cannot be deleted.
      security:
      - securityScheme:
        - write:config_admin_identity_store
      summary: Delete an admin role
      tags:
      - Admin Role
    get:
      description: 'You can get an admin role by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | read:config_admin_identity_store |'
      operationId: get_1
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AdminRoleResponse_AdminRole'
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
      security:
      - securityScheme:
        - read:config_admin_identity_store
      summary: Get an admin role
      tags:
      - Admin Role
    put:
      description: 'You can update an admin role by calling this endpoint. The default admin role cannot be modified.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | write:config_admin_identity_store |'
      operationId: update_1
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminRoleUpsertRequest_AdminRole'
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AdminRoleResponse_AdminRole'
          description: OK
        '400':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Bad Request
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
        '409':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Conflict
      security:
      - securityScheme:
        - write:config_admin_identity_store
      summary: Update an admin role
      tags:
      - Admin Role
components:
  schemas:
    ProblemJson:
      type: object
      properties:
        detail:
          type: string
        entityName:
          type: string
          description: The name of the entity within the error has occurred
        errorKey:
          type: string
          description: A unique identifier of the error
        fieldErrors:
          type: array
          description: Field constraint violation errors
          items:
            $ref: '#/components/schemas/FieldError'
        message:
          type: string
          description: A unique identifier in format of 'error.{errorKey}'
        params:
          type: array
          description: Further information related to the actual error
          items:
            type: object
            additionalProperties:
              type: object
        path:
          type: string
          description: Request URI
        status:
          type: integer
          description: Status code
          format: int32
        title:
          type: string
      description: Based on [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807)
    AdminRoleResponse:
      type: object
      properties:
        description:
          type: string
        id:
          type: string
        name:
          type: string
        scopes:
          uniqueItems: true
          type: array
          items:
            type: string
    ScopeAdminResponse_AdminRole:
      type: object
      properties:
        category:
          type: string
        delete:
          type: string
          description: Scope to delete the specified entity. The field is missing when there is no such scope.
        name:
          type: string
        read:
          type: string
          description: Scope to read the specified entity. The field is missing when there is no such scope.
        write:
          type: string
          description: Scope to write the specified entity. The field is missing when there is no such scope.
    PageMetadata:
      type: object
      properties:
        number:
          type: integer
          format: int64
        size:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
    FieldError:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
        objectName:
          type: string
    AdminRole_InsertRequest:
      required:
      - name
      - scopes
      type: object
      properties:
        description:
          maxLength: 1024
          minLength: 0
          type: string
        name:
          maxLength: 64
          minLength: 3
          pattern: ^$|^[\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*°]([\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*° ]*[\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*°])?$
          type: string
        scopes:
          uniqueItems: true
          type: array
          items:
            type: string
    AdminRoleUpsertRequest_AdminRole:
      required:
      - id
      - name
      - scopes
      type: object
      properties:
        description:
          maxLength: 1024
          minLength: 0
          type: string
        id:
          type: string
        name:
          maxLength: 64
          minLength: 3
          pattern: ^$|^[\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*°]([\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*° ]*[\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*°])?$
          type: string
        scopes:
          uniqueItems: true
          type: array
          items:
            type: string
    PagedModelAdminRoleResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/AdminRoleResponse'
        page:
          $ref: '#/components/schemas/PageMetadata'
    AdminRoleResponse_AdminRole:
      type: object
      properties:
        description:
          type: string
        id:
          type: string
        name:
          type: string
        scopes:
          uniqueItems: true
          type: array
          items:
            type: string
  securitySchemes:
    securityScheme:
      scheme: bearer
      type: http
