openapi: 3.2.0
info:
  description: API documentation of Admin Portal
  title: Admin Portal Dialect API
  version: v0.0.1
servers:
- url: https://{tenant}
  variables:
    tenant:
      default: example.strivacity.com
      description: Your Strivacity tenant
tags:
- name: Dialect
paths:
  /admin/api/v1/claim/dialects:
    get:
      description: 'You can list the existing dialects by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | read:config_claim |'
      operationId: getDialects
      parameters:
      - description: Tags used for filtering must exactly match the tag name
        in: query
        name: policyTags
        required: false
        schema:
          uniqueItems: true
          type: array
          items:
            type: string
      - description: Name used for filtering
        in: query
        name: name
        required: false
        schema:
          type: string
      - description: Zero-based page index (0..N)
        in: query
        name: page
        schema:
          type: integer
          format: int64
          default: 0
      - description: The size of the page to be returned
        in: query
        name: size
        schema:
          type: integer
          format: int64
          default: 20
      - description: 'Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'
        in: query
        name: sort
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PagedModelDialectResponse'
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
      security:
      - securityScheme:
        - read:config_claim
      summary: List dialects
      tags:
      - Dialect
    post:
      description: 'You can create a dialect by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | write:config_claim |'
      operationId: createDialect
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dialect_InsertRequest'
        required: true
      responses:
        '201':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DialectResponse_Dialect'
          description: Created
        '400':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Bad Request
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '409':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Conflict
      security:
      - securityScheme:
        - write:config_claim
      summary: Create a dialect
      tags:
      - Dialect
  /admin/api/v1/claim/dialects/{id}:
    delete:
      description: 'You can delete a dialect by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | delete:config_claim |'
      operationId: deleteDialectById
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No Content
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '409':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Dialect is assigned to an application client
      security:
      - securityScheme:
        - delete:config_claim
      summary: Delete a dialect
      tags:
      - Dialect
    get:
      description: 'You can get a dialect by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | read:config_claim |'
      operationId: getDialect
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DialectResponse_Dialect'
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
      security:
      - securityScheme:
        - read:config_claim
      summary: Get a dialect
      tags:
      - Dialect
    put:
      description: 'You can update a dialect by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | write:config_claim |'
      operationId: updateDialect
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DialectUpdateRequest_Dialect'
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DialectResponse_Dialect'
          description: OK
        '400':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Bad Request
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
        '409':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Conflict
      security:
      - securityScheme:
        - write:config_claim
      summary: Update a dialect
      tags:
      - Dialect
components:
  schemas:
    ProblemJson:
      type: object
      properties:
        detail:
          type: string
        entityName:
          type: string
          description: The name of the entity within the error has occurred
        errorKey:
          type: string
          description: A unique identifier of the error
        fieldErrors:
          type: array
          description: Field constraint violation errors
          items:
            $ref: '#/components/schemas/FieldError'
        message:
          type: string
          description: A unique identifier in format of 'error.{errorKey}'
        params:
          type: array
          description: Further information related to the actual error
          items:
            type: object
            additionalProperties:
              type: object
        path:
          type: string
          description: Request URI
        status:
          type: integer
          description: Status code
          format: int32
        title:
          type: string
      description: Based on [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807)
    DialectResponse:
      type: object
      properties:
        description:
          type: string
        dialectUri:
          type: string
        id:
          type: string
        name:
          type: string
        policyTag:
          type: string
    PageMetadata:
      type: object
      properties:
        number:
          type: integer
          format: int64
        size:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
    FieldError:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
        objectName:
          type: string
    DialectReference_Dialect:
      required:
      - id
      type: object
      properties:
        id:
          pattern: ^[a-zA-Z0-9-]{1,36}$
          type: string
          description: ID of the represented entity
    DialectResponse_Dialect:
      type: object
      properties:
        description:
          type: string
        dialectUri:
          type: string
        id:
          type: string
        name:
          type: string
        policyTag:
          type: string
    PagedModelDialectResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/DialectResponse'
        page:
          $ref: '#/components/schemas/PageMetadata'
    DialectUpdateRequest_Dialect:
      required:
      - dialectUri
      - id
      - name
      type: object
      properties:
        description:
          maxLength: 1024
          minLength: 0
          type: string
        dialectUri:
          minLength: 1
          type: string
        id:
          type: string
        name:
          maxLength: 256
          minLength: 3
          pattern: ^$|^[\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*°]([\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*° ]*[\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*°])?$
          type: string
        policyTag:
          pattern: ^[a-z0-9_]{2,32}$
          type: string
          description: Must be an existing policy tag name
    Dialect_InsertRequest:
      required:
      - dialectUri
      - name
      type: object
      properties:
        description:
          maxLength: 1024
          minLength: 0
          type: string
        dialect:
          $ref: '#/components/schemas/DialectReference_Dialect'
        dialectUri:
          minLength: 1
          type: string
        name:
          maxLength: 256
          minLength: 3
          pattern: ^$|^[\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*°]([\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*° ]*[\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*°])?$
          type: string
        policyTag:
          pattern: ^[a-z0-9_]{2,32}$
          type: string
          description: Must be an existing policy tag name
  securitySchemes:
    securityScheme:
      scheme: bearer
      type: http
