openapi: 3.2.0
info:
  description: API documentation of Admin Portal
  title: Admin Portal Native Claim API
  version: v0.0.1
servers:
- url: https://{tenant}
  variables:
    tenant:
      default: example.strivacity.com
      description: Your Strivacity tenant
tags:
- name: Native Claim
paths:
  /admin/api/v1/claim/native:
    get:
      description: You can list the existing native claims by calling this endpoint.
      operationId: getAllNativeClaims
      parameters:
      - description: Name used for filtering
        in: query
        name: name
        required: false
        schema:
          type: string
      - description: Zero-based page index (0..N)
        in: query
        name: page
        schema:
          type: integer
          format: int64
          default: 0
      - description: The size of the page to be returned
        in: query
        name: size
        schema:
          type: integer
          format: int64
          default: 20
      - description: 'Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'
        in: query
        name: sort
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PagedModelNativeClaimResponse'
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
      security:
      - securityScheme: []
      summary: List native claims
      tags:
      - Native Claim
    post:
      description: 'You can create a native claim by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | write:config_claim |'
      operationId: createNativeClaim
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NativeClaim_InsertRequest'
        required: true
      responses:
        '201':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NativeClaimResponse_NativeClaim'
          description: Created
        '400':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Bad Request
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '409':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Conflict
      security:
      - securityScheme:
        - write:config_claim
      summary: Create a native claim
      tags:
      - Native Claim
  /admin/api/v1/claim/native/{id}:
    delete:
      description: 'You can delete a native claim by calling this endpoint. Native claims assigned to account attributes cannot be deleted.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | delete:config_claim |'
      operationId: deleteNativeClaim
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No Content
        '400':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Bad Request
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '409':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: The native claim is assigned to an account attribute and couldn't be deleted
      security:
      - securityScheme:
        - delete:config_claim
      summary: Delete a native claim
      tags:
      - Native Claim
    get:
      description: 'You can get a native claim by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | read:config_claim |'
      operationId: getNativeClaim
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NativeClaimResponse_NativeClaim'
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
      security:
      - securityScheme:
        - read:config_claim
      summary: Get a native claim
      tags:
      - Native Claim
    put:
      description: 'You can update a native claim by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | write:config_claim |'
      operationId: updateNativeClaim
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NativeClaim_NativeClaim'
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NativeClaimResponse_NativeClaim'
          description: OK
        '400':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Bad Request
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
        '409':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Conflict
      security:
      - securityScheme:
        - write:config_claim
      summary: Update a native claim
      tags:
      - Native Claim
components:
  schemas:
    ProblemJson:
      type: object
      properties:
        detail:
          type: string
        entityName:
          type: string
          description: The name of the entity within the error has occurred
        errorKey:
          type: string
          description: A unique identifier of the error
        fieldErrors:
          type: array
          description: Field constraint violation errors
          items:
            $ref: '#/components/schemas/FieldError'
        message:
          type: string
          description: A unique identifier in format of 'error.{errorKey}'
        params:
          type: array
          description: Further information related to the actual error
          items:
            type: object
            additionalProperties:
              type: object
        path:
          type: string
          description: Request URI
        status:
          type: integer
          description: Status code
          format: int32
        title:
          type: string
      description: Based on [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807)
    PageMetadata:
      type: object
      properties:
        number:
          type: integer
          format: int64
        size:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
    NativeClaim_NativeClaim:
      required:
      - displayName
      - id
      - name
      type: object
      properties:
        description:
          maxLength: 1024
          minLength: 0
          type: string
        dialectUri:
          type: string
          default: http://strivacity.com/claims
        displayName:
          maxLength: 64
          minLength: 3
          pattern: ^$|^[\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*°]([\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*° ]*[\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*°])?$
          type: string
        id:
          type: string
        name:
          maxLength: 256
          minLength: 1
          pattern: ^[a-zA-Z][a-zA-Z0-9_!#$&'()*+,\/:;=?@\[\].]*$
          type: string
        readonly:
          type: boolean
          readOnly: true
    NativeClaim_InsertRequest:
      required:
      - displayName
      - name
      type: object
      properties:
        description:
          maxLength: 1024
          minLength: 0
          type: string
        dialectUri:
          type: string
          default: http://strivacity.com/claims
        displayName:
          maxLength: 64
          minLength: 3
          pattern: ^$|^[\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*°]([\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*° ]*[\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*°])?$
          type: string
        name:
          maxLength: 256
          minLength: 1
          pattern: ^[a-zA-Z][a-zA-Z0-9_!#$&'()*+,\/:;=?@\[\].]*$
          type: string
        readonly:
          type: boolean
          readOnly: true
    PagedModelNativeClaimResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/NativeClaimResponse'
        page:
          $ref: '#/components/schemas/PageMetadata'
    FieldError:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
        objectName:
          type: string
    NativeClaimResponse_NativeClaim:
      type: object
      properties:
        description:
          type: string
        dialectUri:
          type: string
        displayName:
          type: string
        id:
          type: string
        name:
          type: string
        readonly:
          type: boolean
        targetReadonly:
          type: boolean
    NativeClaimResponse:
      type: object
      properties:
        description:
          type: string
        dialectUri:
          type: string
        displayName:
          type: string
        id:
          type: string
        name:
          type: string
        readonly:
          type: boolean
        targetReadonly:
          type: boolean
  securitySchemes:
    securityScheme:
      scheme: bearer
      type: http
