openapi: 3.2.0
info:
  description: API documentation of Admin Portal - Admin Management
  title: Admin Portal - Admin Management Admin External Login…
  version: v0.0.1
servers:
- url: https://{tenant}
  variables:
    tenant:
      default: example.strivacity.com
      description: Your Strivacity tenant
tags:
- name: Admin External Login Mapping
paths:
  /admin/api/v1/admin/loginProviders/{providerId}/availableNativeClaims:
    get:
      description: 'You can list the available native claims for an admin external login provider by calling this endpoint. A native claim is listed if it''s not assigned to an external login provider. A native claim with name `id` will not be listed.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | read:config_admin_login_provider |'
      operationId: getNotAssignedNativeClaims
      parameters:
      - in: path
        name: providerId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                uniqueItems: true
                type: array
                items:
                  $ref: '#/components/schemas/NameIdAndDisplayName'
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
      security:
      - securityScheme:
        - read:config_admin_login_provider
      summary: List available native claims
      tags:
      - Admin External Login Mapping
  /admin/api/v1/admin/loginProviders/{providerId}/mappings:
    get:
      description: 'You can list the claim mappings for an admin external login provider by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | read:config_admin_login_provider |'
      operationId: getEnterpriseLoginMappings
      parameters:
      - in: path
        name: providerId
        required: true
        schema:
          type: string
      - description: Zero-based page index (0..N)
        in: query
        name: page
        schema:
          type: integer
          format: int64
          default: 0
      - description: The size of the page to be returned
        in: query
        name: size
        schema:
          type: integer
          format: int64
          default: 20
      - description: 'Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'
        in: query
        name: sort
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PagedModelExternalLoginMappingResponse'
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
      security:
      - securityScheme:
        - read:config_admin_login_provider
      summary: List claim mappings
      tags:
      - Admin External Login Mapping
    post:
      description: 'You can create a mapping to a native claim for an admin external login provider by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | write:config_admin_login_provider |'
      operationId: createEnterpriseLoginMapping
      parameters:
      - in: path
        name: providerId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalLogin_Mapping_InsertRequest'
        required: true
      responses:
        '201':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExternalLoginMappingResponse'
          description: Created
        '400':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Bad Request
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
        '409':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Native claim mapping already assigned to login provider
      security:
      - securityScheme:
        - write:config_admin_login_provider
      summary: Create a claim mapping
      tags:
      - Admin External Login Mapping
  /admin/api/v1/admin/loginProviders/{providerId}/mappings/{id}:
    delete:
      description: 'You can delete a claim mapping for an admin external login provider by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | delete:config_admin_login_provider |'
      operationId: delete
      parameters:
      - in: path
        name: providerId
        required: true
        schema:
          type: string
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No Content
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
      security:
      - securityScheme:
        - delete:config_admin_login_provider
      summary: Delete claim mapping
      tags:
      - Admin External Login Mapping
    get:
      description: 'You can get a claim mapping for an admin external login provider by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | read:config_admin_login_provider |'
      operationId: getEnterpriseLoginMapping
      parameters:
      - in: path
        name: providerId
        required: true
        schema:
          type: string
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExternalLoginMappingResponse'
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
      security:
      - securityScheme:
        - read:config_admin_login_provider
      summary: Get a claim mapping
      tags:
      - Admin External Login Mapping
    put:
      description: 'You can update a claim mapping for an admin external login provider by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | write:config_admin_login_provider |'
      operationId: updateGenericOIDCMapping
      parameters:
      - in: path
        name: providerId
        required: true
        schema:
          type: string
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalLoginMappingUpsertRequest'
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExternalLoginMappingResponse'
          description: OK
        '400':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Bad Request
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
        '409':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Native claim mapping already assigned to login provider
      security:
      - securityScheme:
        - write:config_admin_login_provider
      summary: Update claim mapping
      tags:
      - Admin External Login Mapping
components:
  schemas:
    ProblemJson:
      type: object
      properties:
        detail:
          type: string
        entityName:
          type: string
          description: The name of the entity within the error has occurred
        errorKey:
          type: string
          description: A unique identifier of the error
        fieldErrors:
          type: array
          description: Field constraint violation errors
          items:
            $ref: '#/components/schemas/FieldError'
        message:
          type: string
          description: A unique identifier in format of 'error.{errorKey}'
        params:
          type: array
          description: Further information related to the actual error
          items:
            type: object
            additionalProperties:
              type: object
        path:
          type: string
          description: Request URI
        status:
          type: integer
          description: Status code
          format: int32
        title:
          type: string
      description: Based on [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807)
    PageMetadata:
      type: object
      properties:
        number:
          type: integer
          format: int64
        size:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
    FieldError:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
        objectName:
          type: string
    ExternalLoginMappingResponse:
      type: object
      properties:
        enabled:
          type: boolean
        fieldValueRegex:
          type: string
        id:
          type: string
        nativeClaim:
          $ref: '#/components/schemas/NameIdAndDisplayName'
        sourcePath:
          type: string
    ExternalLogin_Mapping_InsertRequest:
      required:
      - nativeClaim
      - sourcePath
      type: object
      properties:
        enabled:
          type: boolean
          default: false
        fieldValueRegex:
          type: string
        nativeClaim:
          $ref: '#/components/schemas/IdReferenceRequest'
        sourcePath:
          maxLength: 256
          minLength: 0
          type: string
    IdReferenceRequest:
      required:
      - id
      type: object
      properties:
        id:
          pattern: ^[a-zA-Z0-9-]{1,36}$
          type: string
          description: ID of the represented entity
    ExternalLoginMappingUpsertRequest:
      required:
      - id
      - nativeClaim
      - sourcePath
      type: object
      properties:
        enabled:
          type: boolean
          default: false
        fieldValueRegex:
          type: string
        id:
          type: string
        nativeClaim:
          $ref: '#/components/schemas/IdReferenceRequest'
        sourcePath:
          maxLength: 256
          minLength: 0
          type: string
    PagedModelExternalLoginMappingResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/ExternalLoginMappingResponse'
        page:
          $ref: '#/components/schemas/PageMetadata'
    NameIdAndDisplayName:
      type: object
      properties:
        displayName:
          type: string
          description: Display name of the represented entity
        id:
          type: string
          description: ID of the represented entity
        name:
          type: string
          description: Name of the represented entity
  securitySchemes:
    securityScheme:
      scheme: bearer
      type: http
