openapi: 3.2.0
info:
  description: API documentation of Admin Portal
  title: Admin Portal Account Invitation API
  version: v0.0.1
servers:
- url: https://{tenant}
  variables:
    tenant:
      default: example.strivacity.com
      description: Your Strivacity tenant
tags:
- name: Account Invitation
paths:
  /admin/api/v1/identityStores/{identityStoreName}/invite:
    get:
      description: 'You can list the existing account invitations by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | read:account |'
      operationId: getAccountInvitations
      parameters:
      - in: path
        name: identityStoreName
        required: true
        schema:
          type: string
      - description: Invitation has been accepted or not
        in: query
        name: accepted
        required: false
        schema:
          type: boolean
      - description: Invitation email used for filtering
        in: query
        name: email
        required: false
        schema:
          type: string
      - description: Organization ID used for filtering
        in: query
        name: organization
        required: false
        schema:
          type: string
      - description: Unique identifier organization ID used for filtering
        in: query
        name: organizationScope
        required: false
        schema:
          type: string
      - description: Zero-based page index (0..N)
        in: query
        name: page
        schema:
          type: integer
          format: int64
          default: 0
      - description: The size of the page to be returned
        in: query
        name: size
        schema:
          type: integer
          format: int64
          default: 20
      - description: 'Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'
        in: query
        name: sort
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountInvitationResponse_Account'
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
      security:
      - securityScheme:
        - read:account
      summary: List account invitations
      tags:
      - Account Invitation
    post:
      description: 'You can create an account invitation by calling this endpoint. An invite will be sent to the given email address to register a new account. If the given client doesn''t have a login url, a bad request will be returned. If a pending invitation exists with the given email address, the response contains the existing invitation ID. If an account exists with the given email address and email mismatch is allowed in the Self-service policy, the invitation will be sent.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | write:account |'
      operationId: createInvitation
      parameters:
      - in: path
        name: identityStoreName
        required: true
        schema:
          type: string
      - in: header
        name: X-Skip-Email-Verification
        required: false
        schema:
          type: boolean
      - in: header
        name: X-Skip-Phone-Verification
        required: false
        schema:
          type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountInvitationInsertRequest_AccountInvitationDetails'
        required: true
      responses:
        '201':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AccountInvitationResponse_AccountInvitationDetails'
          description: Created
        '400':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Bad Request
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
        '409':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/InvitationConflictProblemJson_AccountInvitationDetails'
          description: Account with this email identifier already exists and email mismatch is not allowed or an invitation with this email identifier already exists. When an invitation already exists, a `conflictingId` field will be returned in addition, which points to the already existing invitation.
      security:
      - securityScheme:
        - write:account
      summary: Create an account invitation
      tags:
      - Account Invitation
  /admin/api/v1/identityStores/{identityStoreName}/invite/{invitationId}:
    delete:
      description: 'You can revoke an account invitation by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | write:account |'
      operationId: deleteAccountInvitation
      parameters:
      - in: path
        name: identityStoreName
        required: true
        schema:
          type: string
      - in: path
        name: invitationId
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No Content
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
      security:
      - securityScheme:
        - write:account
      summary: Revoke an account invitation
      tags:
      - Account Invitation
    get:
      description: 'You can get an account invitation by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | read:account |'
      operationId: getAccountInvitation
      parameters:
      - in: path
        name: identityStoreName
        required: true
        schema:
          type: string
      - in: path
        name: invitationId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AccountInvitationResponse_AccountInvitationDetails'
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
      security:
      - securityScheme:
        - read:account
      summary: Get an account invitation
      tags:
      - Account Invitation
  /admin/api/v1/identityStores/{identityStoreName}/invite/{invitationId}/resend:
    post:
      description: 'You can resend an account invitation by calling this endpoint. Once an invite is sent, the `validUntil` field is updated.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | write:account |'
      operationId: resendInvitation
      parameters:
      - in: path
        name: identityStoreName
        required: true
        schema:
          type: string
      - in: path
        name: invitationId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AccountInvitationResponse_AccountInvitationDetails'
          description: OK
        '400':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Bad Request
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
      security:
      - securityScheme:
        - write:account
      summary: Resend an account invitation
      tags:
      - Account Invitation
components:
  schemas:
    ProblemJson:
      type: object
      properties:
        detail:
          type: string
        entityName:
          type: string
          description: The name of the entity within the error has occurred
        errorKey:
          type: string
          description: A unique identifier of the error
        fieldErrors:
          type: array
          description: Field constraint violation errors
          items:
            $ref: '#/components/schemas/FieldError'
        message:
          type: string
          description: A unique identifier in format of 'error.{errorKey}'
        params:
          type: array
          description: Further information related to the actual error
          items:
            type: object
            additionalProperties:
              type: object
        path:
          type: string
          description: Request URI
        status:
          type: integer
          description: Status code
          format: int32
        title:
          type: string
      description: Based on [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807)
    FieldError:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
        objectName:
          type: string
    AccountInvitationInsertRequest_AccountInvitationDetails:
      required:
      - clientId
      - email
      - groups
      - language
      - metadata
      - roles
      type: object
      properties:
        clientId:
          minLength: 1
          type: string
          description: ID of the represented client
        email:
          type: string
          format: email
          minLength: 1
        groups:
          type: array
          items:
            $ref: '#/components/schemas/IdReferenceRequest_AccountInvitationDetails'
        language:
          pattern: '[a-z]{2,3}-[A-Z0-9]{2,3}'
          type: string
          default: en-US
        metadata:
          type: object
          additionalProperties:
            type: object
            description: Represents metadata for an account to be invited
          description: Represents metadata for an account to be invited
        organization:
          type: string
          description: ID of the represented organization. If not specified, the invited account will be non-organizational.
        roles:
          type: array
          items:
            $ref: '#/components/schemas/AccountRole_AccountInvitationDetails'
    AccountInvitationResponse_AccountInvitationDetails:
      type: object
      properties:
        accountId:
          type: string
        clientId:
          type: string
          description: ID of the represented client
        email:
          type: string
        groups:
          type: array
          description: List of group ids that are assigned to the account.
          items:
            $ref: '#/components/schemas/IdReferenceResponse_AccountInvitationDetails'
          default: []
        id:
          type: string
        language:
          type: string
          description: Language of the invitation
          default: en-US
        metadata:
          type: object
          additionalProperties:
            type: object
        organization:
          type: string
          description: ID of the represented organization. If not specified, the invited account will be non-organizational.
        roles:
          type: array
          items:
            $ref: '#/components/schemas/AccountRole_AccountInvitationDetails'
        sent:
          type: string
          format: date-time
        store:
          type: string
          description: Name of the represented identity store
        validUntil:
          type: string
          format: date-time
    IdReferenceRequest_AccountInvitationDetails:
      required:
      - id
      type: object
      properties:
        id:
          pattern: ^[a-zA-Z0-9-]{1,36}$
          type: string
          description: ID of the represented entity
    IdReferenceResponse_AccountInvitationDetails:
      type: object
      properties:
        id:
          type: string
          description: ID of the represented entity
    FieldError_AccountInvitationDetails:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
        objectName:
          type: string
    InvitationConflictProblemJson_AccountInvitationDetails:
      type: object
      properties:
        conflictingId:
          type: string
        detail:
          type: string
        entityName:
          type: string
          description: The name of the entity within the error has occurred
        errorKey:
          type: string
          description: A unique identifier of the error
        fieldErrors:
          type: array
          description: Field constraint violation errors
          items:
            $ref: '#/components/schemas/FieldError_AccountInvitationDetails'
        message:
          type: string
          description: A unique identifier in format of 'error.{errorKey}'
        params:
          type: array
          description: Further information related to the actual error
          items:
            type: object
            additionalProperties:
              type: object
        path:
          type: string
          description: Request URI
        status:
          type: integer
          description: Status code
          format: int32
        title:
          type: string
    AccountInvitationResponse_Account:
      type: object
      properties:
        accountId:
          type: string
        clientId:
          type: string
          description: ID of the represented client
        email:
          type: string
        id:
          type: string
        organization:
          type: string
          description: ID of the represented organization. If not specified, the invited account will be non-organizational.
        sent:
          type: string
          format: date-time
        store:
          type: string
          description: Name of the represented identity store
        validUntil:
          type: string
          format: date-time
    AccountRole_AccountInvitationDetails:
      required:
      - id
      - organization
      type: object
      properties:
        id:
          minLength: 1
          type: string
          description: ID of the represented role
        organization:
          minLength: 1
          type: string
          description: ID of the represented organization
      description: Represents an organization-role assignment
  securitySchemes:
    securityScheme:
      scheme: bearer
      type: http
