openapi: 3.2.0
info:
  description: API documentation of Admin Portal
  title: Admin Portal Lifecycle Event Hook Descriptor API
  version: v0.0.1
servers:
- url: https://{tenant}
  variables:
    tenant:
      default: example.strivacity.com
      description: Your Strivacity tenant
tags:
- name: Lifecycle Event Hook Descriptor
paths:
  /admin/api/v1/eventHooks/descriptor:
    get:
      description: 'You can list the possible descriptors for lifecycle event hooks by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | read:config_event_hook |'
      operationId: getAllEventHooks
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventHookDescriptorResponse_EventHookDescriptor'
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
      security:
      - securityScheme:
        - read:config_event_hook
      summary: List descriptors for event hooks
      tags:
      - Lifecycle Event Hook Descriptor
components:
  schemas:
    ProblemJson:
      type: object
      properties:
        detail:
          type: string
        entityName:
          type: string
          description: The name of the entity within the error has occurred
        errorKey:
          type: string
          description: A unique identifier of the error
        fieldErrors:
          type: array
          description: Field constraint violation errors
          items:
            $ref: '#/components/schemas/FieldError'
        message:
          type: string
          description: A unique identifier in format of 'error.{errorKey}'
        params:
          type: array
          description: Further information related to the actual error
          items:
            type: object
            additionalProperties:
              type: object
        path:
          type: string
          description: Request URI
        status:
          type: integer
          description: Status code
          format: int32
        title:
          type: string
      description: Based on [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807)
    FieldError:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
        objectName:
          type: string
    EventHookDescriptorResponse_EventHookDescriptor:
      type: object
      properties:
        blocking:
          type: string
          enum:
          - 'YES'
          - 'NO'
          - USER_DEFINED
        count:
          type: integer
          format: int64
        name:
          type: string
          enum:
          - DENY_AUTHENTICATION
          - UNIDENTIFIED_USER
          - POST_ACCOUNT_LOGIN
          - POST_CONSENT_UPDATE
          - POST_ID_PROOFING
          - POST_IDENTIFICATION
          - POST_MFA_FACTOR_CHANGE
          - POST_REGISTRATION
          - POST_EXTERNAL_LOGIN
          - POST_TOKEN_REFRESH
          - PRE_ID_PROOFING
          - PRE_ID_TOKEN_GENERATION
          - PRE_SAML2_ASSERTION_GENERATION
          - PRE_PROGRESSIVE_PROFILING
          - PRE_REGISTRATION
          - PRE_PASSWORD
          - PRE_PASSWORD_RESET
          - PRE_MULTI_STAGE_REGISTRATION
          - PRE_EXTERNAL_REGISTRATION
          - PRE_AUTHENTICATOR_ENROLLMENT
          - PRE_PASSWORD_PERSIST
          - PRE_CONTACT_UPDATE
          - POST_ACCOUNT_DELETION
          - POST_ACCOUNT_UPDATE
        target:
          type: string
          enum:
          - application
          - identityStore
      description: Represents a descriptor for a lifecycle event hook
  securitySchemes:
    securityScheme:
      scheme: bearer
      type: http
