openapi: 3.2.0
info:
  description: API documentation of Admin Portal
  title: Admin Portal Available Role Scope API
  version: v0.0.1
servers:
- url: https://{tenant}
  variables:
    tenant:
      default: example.strivacity.com
      description: Your Strivacity tenant
tags:
- name: Available Role Scope
paths:
  /admin/api/v1/identityStores/{identityStoreName}/scopes:
    get:
      description: 'You can list the available scopes for a role by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | read:config_identity_store |'
      operationId: getScopes
      parameters:
      - in: path
        name: identityStoreName
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AvailableScopeResponse'
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
      security:
      - securityScheme:
        - read:config_identity_store
      summary: List available scopes
      tags:
      - Available Role Scope
components:
  schemas:
    ProblemJson:
      type: object
      properties:
        detail:
          type: string
        entityName:
          type: string
          description: The name of the entity within the error has occurred
        errorKey:
          type: string
          description: A unique identifier of the error
        fieldErrors:
          type: array
          description: Field constraint violation errors
          items:
            $ref: '#/components/schemas/FieldError'
        message:
          type: string
          description: A unique identifier in format of 'error.{errorKey}'
        params:
          type: array
          description: Further information related to the actual error
          items:
            type: object
            additionalProperties:
              type: object
        path:
          type: string
          description: Request URI
        status:
          type: integer
          description: Status code
          format: int32
        title:
          type: string
      description: Based on [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807)
    AvailableScopeResponse:
      type: object
      properties:
        delete:
          type: string
          description: Delete permission for the scope
        name:
          type: string
        read:
          type: string
          description: Read permission for the scope
        write:
          type: string
          description: Write permission for the scope
      description: Represents an available scope
    FieldError:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
        objectName:
          type: string
  securitySchemes:
    securityScheme:
      scheme: bearer
      type: http
