openapi: 3.2.0
info:
  description: API documentation of Admin Portal
  title: Admin Portal Variables API
  version: v0.0.1
servers:
- url: https://{tenant}
  variables:
    tenant:
      default: example.strivacity.com
      description: Your Strivacity tenant
tags:
- name: Variables
paths:
  /admin/api/v1/instance/variables:
    get:
      description: 'You can list variables by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | read:config_admin_variable |'
      operationId: getAll
      parameters:
      - description: Type used for filtering
        in: query
        name: type
        required: false
        schema:
          type: string
          enum:
          - variable
          - secret
      - description: Tags used for filtering must exactly match the tag name
        in: query
        name: policyTags
        required: false
        schema:
          uniqueItems: true
          type: array
          items:
            type: string
      - description: Name used for filtering
        in: query
        name: name
        required: false
        schema:
          type: string
      - description: Zero-based page index (0..N)
        in: query
        name: page
        schema:
          type: integer
          format: int64
          default: 0
      - description: The size of the page to be returned
        in: query
        name: size
        schema:
          type: integer
          format: int64
          default: 20
      - description: 'Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.'
        in: query
        name: sort
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PagedModelVariableListResponse'
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
      security:
      - securityScheme:
        - read:config_admin_variable
      summary: List variables
      tags:
      - Variables
    post:
      description: 'You can create a variable by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | write:config_admin_variable |'
      operationId: create_5
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/VariableInsertRequest'
              - $ref: '#/components/schemas/SecretVariableInsertRequest'
              - $ref: '#/components/schemas/VariableVariableInsertRequest'
        required: true
      responses:
        '201':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/VariableResponse'
          description: Created
        '400':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Bad Request
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '409':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Conflict
      security:
      - securityScheme:
        - write:config_admin_variable
      summary: Create a variable
      tags:
      - Variables
  /admin/api/v1/instance/variables/{id}:
    delete:
      description: 'You can delete a variable by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | delete:config_admin_variable |'
      operationId: delete_6
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No Content
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '409':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Variable is still in use
      security:
      - securityScheme:
        - delete:config_admin_variable
      summary: Delete a variable
      tags:
      - Variables
    get:
      description: 'You can get a variable by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | read:config_admin_variable |'
      operationId: get_4
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/VariableResponse'
          description: OK
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
      security:
      - securityScheme:
        - read:config_admin_variable
      summary: Get a variable
      tags:
      - Variables
    put:
      description: 'You can update a variable by calling this endpoint.


        | REQUIRED API PERMISSION |

        |:------------------------|

        | write:config_admin_variable |'
      operationId: update_4
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/VariableUpdateRequest'
              - $ref: '#/components/schemas/SecretVariableUpdateRequest'
              - $ref: '#/components/schemas/VariableVariableUpdateRequest'
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/VariableResponse'
          description: OK
        '400':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Bad Request
        '401':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Unauthorized
        '403':
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Forbidden
        '404':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Not Found
        '409':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
          description: Conflict
      security:
      - securityScheme:
        - write:config_admin_variable
      summary: Update a variable
      tags:
      - Variables
components:
  schemas:
    ProblemJson:
      type: object
      properties:
        detail:
          type: string
        entityName:
          type: string
          description: The name of the entity within the error has occurred
        errorKey:
          type: string
          description: A unique identifier of the error
        fieldErrors:
          type: array
          description: Field constraint violation errors
          items:
            $ref: '#/components/schemas/FieldError'
        message:
          type: string
          description: A unique identifier in format of 'error.{errorKey}'
        params:
          type: array
          description: Further information related to the actual error
          items:
            type: object
            additionalProperties:
              type: object
        path:
          type: string
          description: Request URI
        status:
          type: integer
          description: Status code
          format: int32
        title:
          type: string
      description: Based on [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807)
    VariableUpdateRequest:
      required:
      - id
      - name
      - type
      type: object
      properties:
        description:
          maxLength: 1024
          minLength: 0
          type: string
        id:
          type: string
        name:
          maxLength: 64
          minLength: 3
          pattern: ^$|^[\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*°]([\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*° ]*[\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*°])?$
          type: string
        policyTag:
          pattern: ^[a-z0-9_]{2,32}$
          type: string
          description: Must be an existing policy tag name
        type:
          type: string
          enum:
          - variable
          - secret
      discriminator:
        propertyName: type
    PageMetadata:
      type: object
      properties:
        number:
          type: integer
          format: int64
        size:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
    SecretVariableInsertRequest:
      required:
      - name
      - secretValue
      - type
      type: object
      allOf:
      - $ref: '#/components/schemas/VariableInsertRequest'
      - type: object
        properties:
          secretValue:
            maxLength: 8192
            minLength: 0
            type: string
    VariableVariableInsertRequest:
      required:
      - name
      - type
      - value
      type: object
      allOf:
      - $ref: '#/components/schemas/VariableInsertRequest'
      - type: object
        properties:
          value:
            maxLength: 8192
            minLength: 0
            type: string
    FieldError:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
        objectName:
          type: string
    VariableInsertRequest:
      required:
      - name
      - type
      type: object
      properties:
        description:
          maxLength: 1024
          minLength: 0
          type: string
        name:
          maxLength: 64
          minLength: 3
          pattern: ^$|^[\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*°]([\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*° ]*[\p{L}\p{N}\-.:\/_(){}\[\]|&'"?!@+*°])?$
          type: string
        policyTag:
          pattern: ^[a-z0-9_]{2,32}$
          type: string
          description: Must be an existing policy tag name
        type:
          type: string
          enum:
          - variable
          - secret
      discriminator:
        propertyName: type
    PagedModelVariableListResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/VariableListResponse'
        page:
          $ref: '#/components/schemas/PageMetadata'
    SecretVariableUpdateRequest:
      required:
      - id
      - name
      - type
      type: object
      allOf:
      - $ref: '#/components/schemas/VariableUpdateRequest'
      - type: object
        properties:
          secretValue:
            maxLength: 8192
            minLength: 0
            type: string
            description: It will not be overridden unless provided.
    VariableListResponse:
      type: object
      properties:
        description:
          type: string
        id:
          type: string
        name:
          type: string
        policyTag:
          type: string
        type:
          type: string
          enum:
          - variable
          - secret
        valueUpdatedAt:
          type: string
          format: date-time
    VariableVariableUpdateRequest:
      required:
      - id
      - name
      - type
      - value
      type: object
      allOf:
      - $ref: '#/components/schemas/VariableUpdateRequest'
      - type: object
        properties:
          value:
            maxLength: 8192
            minLength: 0
            type: string
    VariableResponse:
      type: object
      properties:
        description:
          type: string
        id:
          type: string
        name:
          type: string
        policyTag:
          type: string
        type:
          type: string
          enum:
          - variable
          - secret
        value:
          type: string
        valueUpdatedAt:
          type: string
          format: date-time
  securitySchemes:
    securityScheme:
      scheme: bearer
      type: http
